import { SetMetadata } from "@nestjs/common";

export enum AdminPermission {
  VIEW_VERIFICATION_QUEUE = "admin:vendors:queue",
  VIEW_VENDOR = "admin:vendors:view",
  VIEW_VENDOR_DOCUMENTS = "admin:vendors:documents",
  APPROVE_VENDOR = "admin:vendors:approve",
  REJECT_VENDOR = "admin:vendors:reject",
  VIEW_ALL_VENDORS = "admin:vendors:list",
  SUSPEND_VENDOR = "admin:vendors:suspend",
  REACTIVATE_VENDOR = "admin:vendors:reactivate",
  VIEW_AUDIT_LOGS = "admin:audit:read",
  MANAGE_ADMIN_USERS = "admin:users:manage",
  MANAGE_CATALOGUE = "admin:catalogue:manage",
  INSURANCE_OPERATING_MODEL_VIEW = "admin:insurance:operating-model:view",
  INSURANCE_OPERATING_MODEL_MANAGE = "admin:insurance:operating-model:manage",
  INSURANCE_ORGANIZATION_VIEW = "admin:insurance:organization:view",
  INSURANCE_ORGANIZATION_CREATE = "admin:insurance:organization:create",
  INSURANCE_ORGANIZATION_REVIEW = "admin:insurance:organization:review",
  INSURANCE_ORGANIZATION_APPROVE = "admin:insurance:organization:approve",
  INSURANCE_ORGANIZATION_SUSPEND = "admin:insurance:organization:suspend",
  INSURANCE_DOCUMENT_VIEW = "admin:insurance:document:view",
  INSURANCE_DOCUMENT_REVIEW = "admin:insurance:document:review",
  INSURANCE_POLICY_TYPE_VIEW = "admin:insurance:policy-type:view",
  INSURANCE_POLICY_TYPE_MANAGE = "admin:insurance:policy-type:manage",
  INSURANCE_DISCLOSURE_VIEW = "admin:insurance:disclosure:view",
  INSURANCE_DISCLOSURE_MANAGE = "admin:insurance:disclosure:manage",
  INSURANCE_CONSENT_TEMPLATE_VIEW = "admin:insurance:consent-template:view",
  INSURANCE_CONSENT_TEMPLATE_MANAGE = "admin:insurance:consent-template:manage",
  INSURANCE_AUDIT_VIEW = "admin:insurance:audit:view",
  INSURANCE_PRODUCT_VIEW = "admin:insurance:product:view",
  INSURANCE_PRODUCT_CREATE = "admin:insurance:product:create",
  INSURANCE_PRODUCT_EDIT = "admin:insurance:product:edit",
  INSURANCE_PRODUCT_SUBMIT = "admin:insurance:product:submit",
  INSURANCE_PRODUCT_REVIEW = "admin:insurance:product:review",
  INSURANCE_PRODUCT_APPROVE = "admin:insurance:product:approve",
  INSURANCE_PRODUCT_REJECT = "admin:insurance:product:reject",
  INSURANCE_PRODUCT_WITHDRAW = "admin:insurance:product:withdraw",
  INSURANCE_PRODUCT_VERSION_CREATE = "admin:insurance:product-version:create",
  INSURANCE_PRODUCT_DOCUMENT_VIEW = "admin:insurance:product-document:view",
  INSURANCE_PRODUCT_DOCUMENT_UPLOAD = "admin:insurance:product-document:upload",
  INSURANCE_PRODUCT_AVAILABILITY_MANAGE = "admin:insurance:product-availability:manage",
  INSURANCE_QUOTE_VIEW = "admin:insurance:quote:view",
  INSURANCE_RATE_CARD_MANAGE = "admin:insurance:rate-card:manage",
  INSURANCE_COMPARISON_VIEW = "admin:insurance:comparison:view",
  INSURANCE_RANKING_VIEW = "admin:insurance:ranking:view",
  INSURANCE_RANKING_MANAGE = "admin:insurance:ranking:manage",
  INSURANCE_INTEGRATION_VIEW = "admin:insurance:integration:view",
  INSURANCE_INTEGRATION_CREATE = "admin:insurance:integration:create",
  INSURANCE_INTEGRATION_EDIT = "admin:insurance:integration:edit",
  INSURANCE_INTEGRATION_ACTIVATE = "admin:insurance:integration:activate",
  INSURANCE_INTEGRATION_SUSPEND = "admin:insurance:integration:suspend",
  INSURANCE_INTEGRATION_HEALTH_VIEW = "admin:insurance:integration:health:view",
  INSURANCE_INTEGRATION_CREDENTIAL_MANAGE = "admin:insurance:integration:credential:manage",
  INSURANCE_PROVIDER_REQUEST_VIEW = "admin:insurance:provider-request:view",
  INSURANCE_PROVIDER_FAILURE_VIEW = "admin:insurance:provider-failure:view",
  INSURANCE_HANDOFF_VIEW = "admin:insurance:handoff:view",
  INSURANCE_HANDOFF_RETRY = "admin:insurance:handoff:retry",
  INSURANCE_PROVIDER_EVENT_VIEW = "admin:insurance:provider-event:view",
  INSURANCE_OPERATIONS_DASHBOARD_VIEW = "admin:insurance:operations:dashboard:view",
  INSURANCE_QUOTE_OPERATIONS_VIEW = "admin:insurance:operations:quote:view",
  INSURANCE_QUOTE_OPERATIONS_RETRY = "admin:insurance:operations:quote:retry",
  INSURANCE_QUOTE_OPERATIONS_RECALCULATE = "admin:insurance:operations:quote:recalculate",
  INSURANCE_PROVIDER_OPERATIONS_VIEW = "admin:insurance:operations:provider:view",
  INSURANCE_PROVIDER_OPERATIONS_HEALTH_CHECK = "admin:insurance:operations:provider:health-check",
  INSURANCE_PROVIDER_OPERATIONS_SUSPEND = "admin:insurance:operations:provider:suspend",
  INSURANCE_PROVIDER_OPERATIONS_REACTIVATE = "admin:insurance:operations:provider:reactivate",
  INSURANCE_CALLBACK_OPERATIONS_VIEW = "admin:insurance:operations:callback:view",
  INSURANCE_CALLBACK_OPERATIONS_REPROCESS = "admin:insurance:operations:callback:reprocess",
  INSURANCE_HANDOFF_OPERATIONS_VIEW = "admin:insurance:operations:handoff:view",
  INSURANCE_HANDOFF_OPERATIONS_RETRY = "admin:insurance:operations:handoff:retry",
  INSURANCE_SUPPORT_VIEW = "admin:insurance:support:view",
  INSURANCE_SUPPORT_SENSITIVE_VIEW = "admin:insurance:support:sensitive:view",
  INSURANCE_EVIDENCE_VIEW = "admin:insurance:evidence:view",
  INSURANCE_EVIDENCE_EXPORT = "admin:insurance:evidence:export",
}

export const PERMISSIONS_KEY = "admin_permissions";

export const Permissions = (...permissions: AdminPermission[]) =>
  SetMetadata(PERMISSIONS_KEY, permissions);
