"use client";

import { Button, Card, ErrorState, LoadingState, PageContainer, PageHeader, StatusBadge } from "@setu/ui";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";

import { ProtectedShell } from "../../../components/protected-shell";
import { AdminApiClientError, adminApi } from "../../../lib/admin-api-client";

export default function CataloguePage() {
  const token = typeof window === "undefined" ? null : sessionStorage.getItem("setu_admin_access_token"); const client = useQueryClient(); const [error, setError] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["admin-catalog"], enabled: Boolean(token), queryFn: () => adminApi.catalog(token ?? "") });
  const refresh = () => void client.invalidateQueries({ queryKey: ["admin-catalog"] });
  const category = useMutation({ mutationFn: (input: { name: string; description?: string }) => adminApi.createCatalogCategory(token ?? "", input), onSuccess: refresh, onError: fail });
  const state = useMutation({ mutationFn: (input: { name: string; code: string }) => adminApi.createCatalogState(token ?? "", input), onSuccess: refresh, onError: fail });
  const city = useMutation({ mutationFn: (input: { name: string; stateId: string }) => adminApi.createCatalogCity(token ?? "", input), onSuccess: refresh, onError: fail });
  const categoryStatus = useMutation({ mutationFn: (input: { id: string; isActive: boolean }) => adminApi.setCatalogCategoryStatus(token ?? "", input.id, input.isActive), onSuccess: refresh, onError: fail });
  const cityStatus = useMutation({ mutationFn: (input: { id: string; isActive: boolean }) => adminApi.setCatalogCityStatus(token ?? "", input.id, input.isActive), onSuccess: refresh, onError: fail });
  function fail(value: unknown) { setError(value instanceof AdminApiClientError ? value.message : "The catalogue change could not be saved."); }
  function form(handler: (input: Record<string, string>) => void) { return (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); handler(Object.fromEntries(data.entries()) as Record<string, string>); event.currentTarget.reset(); }; }
  return <PageContainer><ProtectedShell><PageHeader eyebrow="Discovery data" title="Categories and cities" description="Maintain the public discovery catalogue from a controlled admin workflow. Every write is recorded in the audit log." />
    {query.isLoading ? <LoadingState label="Loading catalogue" /> : null}{query.isError ? <ErrorState title="Catalogue unavailable" detail="This area is limited to operations and super administrators." /> : null}
    {query.data ? <><section className="grid gap-5 lg:grid-cols-3"><Card><h2 className="text-lg font-semibold">Add category</h2><form className="mt-4 space-y-3" onSubmit={form((data) => category.mutate({ name: data.name, description: data.description }))}><input className="w-full rounded-xl border border-slate-200 px-3 py-2" name="name" placeholder="Category name" required /><textarea className="w-full rounded-xl border border-slate-200 px-3 py-2" name="description" placeholder="Optional description" /><Button disabled={category.isPending} type="submit">Add category</Button></form></Card><Card><h2 className="text-lg font-semibold">Add state</h2><form className="mt-4 space-y-3" onSubmit={form((data) => state.mutate({ name: data.name, code: data.code }))}><input className="w-full rounded-xl border border-slate-200 px-3 py-2" name="name" placeholder="State name" required /><input className="w-full rounded-xl border border-slate-200 px-3 py-2" name="code" placeholder="State code, e.g. MH" required /><Button disabled={state.isPending} type="submit">Add state</Button></form></Card><Card><h2 className="text-lg font-semibold">Add city</h2><form className="mt-4 space-y-3" onSubmit={form((data) => city.mutate({ name: data.name, stateId: data.stateId }))}><input className="w-full rounded-xl border border-slate-200 px-3 py-2" name="name" placeholder="City name" required /><select className="w-full rounded-xl border border-slate-200 px-3 py-2" defaultValue="" name="stateId" required><option disabled value="">Select state</option>{query.data.states.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button disabled={city.isPending} type="submit">Add city</Button></form></Card></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="overflow-x-auto p-0"><div className="p-5"><h2 className="text-lg font-semibold">Categories</h2></div><table className="min-w-full text-left text-sm"><thead className="border-y bg-slate-50"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Slug</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody>{query.data.categories.map((item) => <tr className="border-b" key={item.id}><td className="px-4 py-3 font-medium">{item.name}</td><td className="px-4 py-3 text-slate-500">{item.slug}</td><td className="px-4 py-3"><StatusBadge status={item.isActive ? "ACTIVE" : "DISABLED"} /></td><td className="px-4 py-3"><Button disabled={categoryStatus.isPending} onClick={() => categoryStatus.mutate({ id: item.id, isActive: !item.isActive })} size="sm" type="button" variant="outline">{item.isActive ? "Disable" : "Enable"}</Button></td></tr>)}</tbody></table></Card><Card className="overflow-x-auto p-0"><div className="p-5"><h2 className="text-lg font-semibold">Cities</h2></div><table className="min-w-full text-left text-sm"><thead className="border-y bg-slate-50"><tr><th className="px-4 py-3">City</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody>{query.data.cities.map((item) => <tr className="border-b" key={item.id}><td className="px-4 py-3 font-medium">{item.name}</td><td className="px-4 py-3 text-slate-500">{item.state.name}</td><td className="px-4 py-3"><StatusBadge status={item.isActive ? "ACTIVE" : "DISABLED"} /></td><td className="px-4 py-3"><Button disabled={cityStatus.isPending} onClick={() => cityStatus.mutate({ id: item.id, isActive: !item.isActive })} size="sm" type="button" variant="outline">{item.isActive ? "Disable" : "Enable"}</Button></td></tr>)}</tbody></table></Card></section></> : null}{error ? <p className="mt-5 text-sm text-rose-700">{error}</p> : null}
  </ProtectedShell></PageContainer>;
}
